name: Android CI - assembleDebug

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Set up JDK 17 for Android SDK compatibility
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3️⃣ Cache Gradle dependencies
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}
          restore-keys: gradle-

      # 4️⃣ Set up Android SDK (default latest tools)
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      # 5️⃣ Build the debug APK using system Gradle
      - name: Build debug APK
        run: gradle assembleDebug --no-daemon

      # 6️⃣ Upload APK artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
